#!/usr/bin/env sh

set -e

info () { printf "%s\\n" "$*" ; }

warn () { printf "WARNING: %s\\n" "$*" ; }

error() {
  printf '%s\n\n' "$1" >&2
  printf 'Usage: REPO=owner/repo BIN=name %s\n' "$0" >&2
  exit 1
}

if [ -z "${REPO}" ]; then
  error "REPO should be in the form of 'organization/repo', got '${REPO}'."
fi

if [ -z "${BIN}" ]; then
  BIN=$(basename "${REPO}")
fi

BIN_ROOT="$HOME/.local/bin"
MAN_ROOT="$HOME/.local/share/man"
MAN_SECTION="1"
MAN_ARTIFACT_NAME="${BIN}.${MAN_SECTION}"
MAN_DESTINATION="${MAN_ROOT}/man${MAN_SECTION}/${MAN_ARTIFACT_NAME}"
DESTINATION="${BIN_ROOT}/${BIN}"

if [ "$(id -u)" -ne 0 ]; then
  warn "Uninstalling for the current user only. If you want to uninstall for all, run 'sudo $0'."
fi

info "Starting uninstallation of ${BIN}"
info "  Removing binaries and manpages..."
rm -f "${DESTINATION}"
rm -f "${MAN_DESTINATION}"

# check previous installations (the sudo ones) and attempt cleaning
if [ "$(id -u)" -eq 0 ]; then
  rm -f "/usr/local/bin/${BIN}"
  rm -f "/usr/local/share/man/man1/${BIN}.1"
fi

info "  Removing binaries and manpages... OK"

info "Done!"
